[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[dev]
  framework = "vite"
  targetPort = 5173
  port = 8888
  publish = "dist"

[[redirects]]
  from = "/api/webhook/*"
  to = "/.netlify/functions/webhook"
  status = 200
  force = true